name = "lkmo-leaderboard"
main = "worker.js"
compatibility_date = "2023-10-30"

# Set up KV namespace for the leaderboard data.
# Replace the id below with the id of the KV namespace you create using wrangler.
# Run `wrangler kv:namespace create LEADERBOARD_KV` to get the ID.
[[kv_namespaces]]
binding = "LEADERBOARD_KV"
id = "YOUR_KV_NAMESPACE_ID_HERE"
